apiVersion: v1
kind: Pod
metadata:
  name: manual-nginx
  namespace: default
spec:
  nodeName: k8s-internals-worker
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
