apiVersion: v1
kind: Pod
metadata:
  name: labeled-nginx
  namespace: default
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
