apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-day08
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
