apiVersion: v1
kind: Pod
metadata:
  name: pod-local-storage
spec:
  containers:
    - name: log-writer
      image: alpine:3.18
      command: ["/bin/sh", "-c", "while true; do echo $(date) - Local Storage Live Write >> /data/test-logs.txt; sleep 5; done"]
      volumeMounts:
        - name: local-vol
          mountPath: /data
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
  volumes:
    - name: local-vol
      persistentVolumeClaim:
        claimName: local-pvc-day08
