apiVersion: v1
kind: Pod
metadata:
  name: oom-killed-demo
  namespace: default
  labels:
    app: oom-stress
    day: day-02
spec:
  containers:
  - name: memory-hog
    image: polinux/stress:latest
    imagePullPolicy: IfNotPresent
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--timeout", "600s"]
    resources:
      requests:
        cpu: "100m"
        memory: "32Mi"
      limits:
        cpu: "200m"
        memory: "64Mi"  # Specifying 64Mi while stress allocates 150M triggers immediate OOMKill (Exit Code 137)
  restartPolicy: Never
