apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}-config
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  database_host: {{ .Values.customConfig.db_host | quote }}
  database_port: {{ .Values.customConfig.db_port | default "3306" | quote }}
  features_enabled: {{ .Values.customConfig.features_enabled | quote }}
  release_name: {{ .Release.Name | quote }}
  release_namespace: {{ .Release.Namespace | quote }}
