apiVersion: v1
kind: Service
metadata:
  name: web-backend-nodeport
  namespace: default
  labels:
    app: web-backend
spec:
  type: NodePort
  selector:
    app: web-backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
