apiVersion: v1
kind: Service
metadata:
  name: web-backend-loadbalancer
  namespace: default
  labels:
    app: web-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: web-backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  externalTrafficPolicy: Local
