apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system
spec:
  interval: 2h0m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: payment-gateway
  namespace: flux-system
spec:
  interval: 10m0s
  releaseName: payment-gateway
  targetNamespace: dev-env
  chart:
    spec:
      chart: nginx
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Override Chart values declaratively
  values:
    replicaCount: 3
    service:
      type: ClusterIP
      ports:
        http: 80
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
