apiVersion: v1
kind: Namespace
metadata:
  name: security-baseline-apps
  labels:
    # Warn and Audit on baseline standards violations (warn user, write audit logs)
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: security-restricted-apps
  labels:
    # Enforce restricted standards. Pods that violate restricted rules will be rejected by the API Server.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
