apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: payment-project
  source:
    repoURL: 'https://github.com/userhimanshuverma/30-Days-of-Production-Kubernetes.git'
    targetRevision: main
    path: Day-20/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
