apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default-spot
spec:
  template:
    metadata:
      labels:
        finops-tier: tier-3
    spec:
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["arm64", "amd64"] # Support graviton (arm64) instances which are 40% more cost-effective
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot"] # Prioritize spot instances
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["c", "m", "r"] # Compute, general, memory optimized classes
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values: ["5"] # Exclude older, less efficient instances
      nodeClassRef:
        name: default-ec2-node-class
  disruption:
    consolidationPolicy: WhenUnderutilized # Consolidate nodes when they are under-utilized (bin packing)
    expireAfter: 720h # 30 days maximum node lifetime to prevent configuration drift
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default-ec2-node-class
spec:
  amiFamily: Bottlerocket # Container-optimized, highly secure, fast-booting OS
  role: KarpenterNodeRole-my-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: my-cluster
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: my-cluster
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 50Gi
      volumeType: gp3
      iops: 3000
      throughput: 125
      encrypted: true
