apiVersion: v1
kind: Pod
metadata:
  name: debug-toolkit
  namespace: default
  labels:
    app: debug-toolkit
spec:
  containers:
  - name: toolkit
    image: nicolaka/netshoot:latest
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"] # Allows tcpdump and raw socket manipulation
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"
  terminationGracePeriodSeconds: 0
