apiVersion: v1
kind: Pod
metadata:
  name: dns-broken-client
  namespace: default
  labels:
    app: dns-client
spec:
  dnsPolicy: None # Overriding default ClusterFirst policy
  dnsConfig:
    nameservers:
      - 8.8.8.8 # External DNS server that cannot resolve cluster-local services (e.g. order-service.default.svc.cluster.local)
    searches:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
    options:
      - name: ndots
        value: "5"
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "3600"]
