kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: production-platform
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
- role: control-plane
  image: kindest/node:v1.27.3
- role: control-plane
  image: kindest/node:v1.27.3
- role: worker
  image: kindest/node:v1.27.3
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  image: kindest/node:v1.27.3
- role: worker
  image: kindest/node:v1.27.3
networking:
  disableDefaultCNI: false
  kubeProxyMode: "iptables"
