apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-databases-backup
  namespace: velero
spec:
  schedule: "0 1 * * *" # Run every day at 1:00 AM UTC
  template:
    includedNamespaces:
      - databases
      - kafka
    excludedResources:
      - events
    storageLocation: default
    volumeSnapshotLocations:
      - default
    ttl: 720h0m0s # Retain backups for 30 days
    snapshotVolumes: true
