apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-ai-sa
  namespace: ai-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fastapi-ai-role
  namespace: ai-services
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-ai-rolebinding
  namespace: ai-services
subjects:
  - kind: ServiceAccount
    name: fastapi-ai-sa
    namespace: ai-services
roleRef:
  kind: Role
  name: fastapi-ai-role
  apiGroup: rbac.authorization.k8s.io
