apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: ai-services
spec:
  provider:
    vault:
      server: "http://vault.security.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "fastapi-ai-role"
          serviceAccountRef:
            name: fastapi-ai-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fastapi-database-secrets
  namespace: ai-services
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-secrets-sync
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: production/database
        property: db-user
    - secretKey: password
      remoteRef:
        key: production/database
        property: db-password
